[general]
name = "non-maximum-suppression"
version = 1
license = "Apache-2.0"
backends = ["cuda"]

[general.hub]
repo-id = "aymuos15/non-maximum-suppression"

[torch]
src = [
    "torch-ext/torch_binding.cpp",
    "torch-ext/torch_binding.h",
]

[kernel.non_maximum_suppression]
backend = "cuda"
depends = ["torch"]
src = ["csrc/non_maximum_suppression.cu"]
