[general]
name = "rmsnorm"
version = 1
license = "Apache-2.0"
backends = ["cuda"]

[general.hub]
repo-id = "kernels-local/rmsnorm"

[torch]
src = [
    "torch-ext/torch_binding.cpp",
    "torch-ext/torch_binding.h",
]

[kernel.rmsnorm]
backend = "cuda"
depends = ["torch"]
src = ["csrc/rmsnorm.cu"]
