[general]
name = "qwen3-next-gated-rmsnorm"
version = 1
license = "Apache-2.0"
backends = ["cuda"]

[general.hub]
repo-id = "aymuos15/qwen3-next-gated-rmsnorm"

[torch]
src = [
    "torch-ext/torch_binding.cpp",
    "torch-ext/torch_binding.h",
]

[kernel.qwen3_next_gated_rmsnorm]
backend = "cuda"
depends = ["torch"]
src = ["csrc/qwen3_next_gated_rmsnorm.cu"]
