[general]
name = "nms"
version = 1
license = "Apache-2.0"
backends = ["cuda"]

[general.hub]
repo-id = "kernels-local/nms"

[torch]
src = [
    "torch-ext/torch_binding.cpp",
    "torch-ext/torch_binding.h",
]

[kernel.nms]
backend = "cuda"
depends = ["torch"]
src = ["csrc/nms.cu"]
