[general]
name = "cohere2-moe-experts"
version = 1
license = "Apache-2.0"
backends = ["cuda"]

[general.hub]
repo-id = "aymuos15/cohere2-moe-experts"

[torch]
src = [
    "torch-ext/torch_binding.cpp",
    "torch-ext/torch_binding.h",
]

[kernel.cohere2_moe_experts]
backend = "cuda"
depends = ["torch"]
src = ["csrc/cohere2_moe_experts.cu"]
